# Wikipedia (ja)
wp: 'http://ja.wikipedia.org/wiki/%s'

# OpenPNE Plugins
opplug: 'http://plugins.openpne.jp/package/%s'

# 接頭辞が省略された場合のデフォルトのリンク先
default: 'http://example.com/wiki/%s'


<?php $base = sfConfig::get('op_base_url'); ?>

# SNS内へのリンク
member: <?php echo $base.'member/%s'."\n"; ?>
commu: <?php echo $base.'community/%s'."\n"; ?>
communuty: <?php echo $base.'community/%s'."\n"; ?>

## 以下は別途プラグインが必要
# opDiaryPlugin
diary: <?php echo $base.'diary/%s'."\n"; ?>

# opAlbumPlugin
album: <?php echo $base.'album/%s'."\n"; ?>

#opCommunityTopicPlugin
topic: <?php echo $base.'communityTopic/%s'."\n"; ?>
event: <?php echo $base.'communityEvent/%s'."\n"; ?>

